### ISSUE TITLE
README.alphapickle

### ISSUE THREAD

**Issue by tshum-05** [mattarnoldbio/alphapickle#2]
Hi, I can't seem to find the README.alphapickle file that contains specific instructions for usage. Could you please provide an example code of running the program? Thanks so much.

**Comment by mattarnoldbio** [comment]
Hi! I will update the README.md file to include specific usage instructions at some point today. I'll admit, I was a little skeptical that anyone else would actually use this when I wrote it, which is why the instructions are a little shoddy. I'll close this issue when I have done it! Thanks for your feedback!

**Comment by mattarnoldbio** [comment]
All sorted now, please let me know if you have any other problems or feature requests!

**Comment by tshum-05** [comment]
Thanks so much, appreciate it!
