### ISSUE TITLE
Bus error during generating PAE plots

### ISSUE THREAD

**Issue by canfeng-HUA** [mattarnoldbio/alphapickle#4]
Thank you very much for providing us with such great tools!

I have a very stupid question for you. I cannot generate PAE plots by using alphapickle, but I can generate pLDDT plots.

The code for PAE is:

> <img width="697" alt="image" src="https://user-images.githubusercontent.com/71436402/160183527-6d7a8a5a-42cf-4519-a4f7-e886e8201cfd.png">

**The version of alphafold is: module load AlphaFold/2.1.2-fosscuda-2020b-uniclust30_2020_06
The version of Python is: Python 3.8.6**

Could you please help me fix it?

**Comment by mattarnoldbio** [comment]
Hi! Glad to hear that this has been useful to you. The bus error is not one I have seen before. Would you mind seeing if this still happens if you include the absolute file path to your .pkl file (starting from your ~ directory). Let me know if that solves it and if not I'll look into it further.

**Comment by canfeng-HUA** [comment]
Thanks a lot for your suggestion. I try the absolute file path, but it still returns the same error.

**Comment by mattarnoldbio** [comment]
Hi! Not to worry then, I'll investigate this further next week.

**Comment by canfeng-HUA** [comment]
Thank you very much. Looking forward to it.

**Comment by mattarnoldbio** [comment]
Hi @canfeng-HUA 
This is interesting. As I suspected at first glance the other day, `bus error` refers to a system error not a python error and is likely caused by your computer trying to allocate memory it does not have access to (either because there is not enough RAM or because the thing pointing to the memory is broken). 
There are a number of possible causes for this. I have a few questions:

- How long is the sequence (or sequences) that you have predicted and are trying to process the metadata from?

- What is the size on your disk of the .pkl file?

Can I request that you pull the most recent commit (`148acbd`) and navigate to [...]/AlphaPickle/debug. From there, please run the command `python run_DebugAlphaPickle.py -pf the_absolute_path_to_your_pkl_file` and copy and paste the full terminal output into a reply to this post.

I have added print statements with checkpoints in the code to allow me to figure out exactly where the program is falling down.

**Comment by canfeng-HUA** [comment]
The length of my sequence is 1168. 
The size of my .pkl file is 1.1G.
The RAM of my service is:
![image](https://user-images.githubusercontent.com/71436402/160711370-d7556c72-225a-4622-a598-32b35d998eb0.png)

The terminal debugs terminal output is:
![image](https://user-images.githubusercontent.com/71436402/160711496-efc82335-ef5a-4379-82c4-4d7232a8dac7.png)

**Comment by mattarnoldbio** [comment]
Ok, like I thought, the part which is causing the problems is the deserialisation of the pickle file. Would you be willing to share your .pkl file? It might be easier for me to solve this if you can? My email address is m.arnold.1@research.gla.ac.uk

If not, it might be possible to use the [Colab notebook](https://colab.research.google.com/github/mattarnoldbio/alphapickle/blob/main/AlphaPickle.ipynb) as a one-off way around this issue, as long as your internet connection is sufficient to upload a 1.1GB file. However, I appreciate this is not an ideal workaround if you have multiple files you want to process.

**Comment by canfeng-HUA** [comment]
Sure. I send the .pkl file to you through my gmail.
